### ISSUE TITLE
Getting the following error:

### ISSUE THREAD

**Issue by Deatojef** [TheKoola/eosstracker#59]
Getting the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/eosstracker/bin/gpspoller.py", line 939, in runGPSPoller
    g.run()
  File "/eosstracker/bin/gpspoller.py", line 542, in run
    gpsDeviceFound = self.gpsActivation(gpsd = gpsd, retrylimit = 100)
  File "/eosstracker/bin/gpspoller.py", line 406, in gpsActivation
    datetime_record = self.createDateString(gpsd.utc)
  File "/eosstracker/bin/gpspoller.py", line 280, in createDateString
    utc_datetime = datetime.datetime.now(datetime.UTC)
AttributeError: module 'datetime' has no attribute 'UTC'
```
Noticed after merged gpsunblock pull request to brickv2.1... 

Running on `Ubuntu 22.04.4 LTS` with `Python 3.10.12`.

_Originally posted by @TheKoola in https://github.com/TheKoola/eosstracker/issues/58_

**Comment by Deatojef** [comment]
Looks to be due to Python versions.  From docs.python.org:

```
datetime.UTC¶
Alias for the UTC time zone singleton datetime.timezone.utc.

Added in version 3.11.
```
